Contactenlijst/Entities/Contact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

namespace Contactenlijst.Entities {
	public class Contact {
		public string Name { get; set; }
		public string LastName { get; set; }
		public DateTime DateOfBirth { get; set; }
		public List<string> Emails { get; set; }
		public List<string> PhoneNumbers { get; set; }
		public List<Address> Addresses { get; set; }
		public string Comment { get; set; }
		public Guid Guid { get; set; }
	}
}

Contactenlijst/Controllers/ContactController.cs
using Contactenlijst.Database;
using Contactenlijst.Entities;
using Contactenlijst.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;

namespace Contactenlijst.Controllers {
	public class ContactController : Controller {
		private readonly IContactDatabase _contactDatabase = new ContactDatabase( );

		public IActionResult Index( ) {
			List<ContactIndexViewModel> viewModels = new List<ContactIndexViewModel>();

			foreach (Contact contact in _contactDatabase.GetContacts( ))
				viewModels.Add(new ContactIndexViewModel {
					Name = contact.Name,
					LastName = contact.LastName,
					Guid = contact.Guid
				});

			viewModels = viewModels.OrderBy(c => c.LastName).ThenBy(c => c.Name).ToList( );

			return View(viewModels);
		}

		[HttpGet]
		public IActionResult Create( ) {
			ContactCreateViewModel viewModel = new ContactCreateViewModel() { DateOfBirth = DateTime.Now};

			viewModel.PhoneNumbers.Add(new PhoneNumberViewModel( ));
			viewModel.Emails.Add(new EmailViewModel( ));
			viewModel.Addresses.Add(new AddressViewModel( ) { Guid = Guid.NewGuid( ), RemoveRemoveButton = true });

			return View(viewModel);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create([FromForm] ContactCreateViewModel contactCreateViewModel) {

			// TODO: finish creating a contact

			if (!TryValidateModel(contactCreateViewModel)) {
				return View(contactCreateViewModel);
			}

			_contactDatabase.Insert(new Contact {
				Name = contactCreateViewModel.FirstName,
				LastName = contactCreateViewModel.LastName,
				DateOfBirth = contactCreateViewModel.DateOfBirth,
				Emails = contactCreateViewModel.Emails.Select(x => x.Value).Where(x => !string.IsNullOrWhiteSpace(x)).ToList( ),
				PhoneNumbers = contactCreateViewModel.PhoneNumbers.Select(x => x.Value).Where(x => !string.IsNullOrWhiteSpace(x)).ToList( ),
				Addresses = contactCreateViewModel.Addresses.Select(x => new Address( ) {
					City = x.City,
					ZipCode = x.ZipCode,
					AddressLine1 = x.AddressLine1,
					AddressLine2 = x.AddressLine2,
					Guid = x.Guid
				}).ToList( ),
				Comment = contactCreateViewModel.Comment,
				Guid = Guid.NewGuid( )
			});

			return RedirectToAction(nameof(Index));
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult AddEmailItem([FromForm] ContactCreateViewModel contactCreateViewModel) {
			contactCreateViewModel.Emails.Add(new EmailViewModel( ));
			return PartialView("EmailItem", contactCreateViewModel);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult AddPhoneNumberItem([FromForm] ContactCreateViewModel contactCreateViewModel) {
			contactCreateViewModel.PhoneNumbers.Add(new PhoneNumberViewModel( ));
			return PartialView("PhoneNumberItem", contactCreateViewModel);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult AddAddressItem([FromForm] ContactCreateViewModel contactCreateViewModel) {
			contactCreateViewModel.Addresses.Add(new AddressViewModel( ) { Guid = Guid.NewGuid( ) });
			return PartialView("AdressItem", contactCreateViewModel);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult RemoveAddressItem(Guid id, [FromForm] ContactCreateViewModel contactCreateViewModel) {
			AddressViewModel addressViewModel = contactCreateViewModel.Addresses.FirstOrDefault(x => x.Guid == id);

			if (!(addressViewModel is null)) {
				contactCreateViewModel.Addresses.Remove(addressViewModel);
				return Json(new { success = true, responseText = "" });
			} else {
				return Json(new { success = false, responseText = "Could not find address" });
			}
		}
	}
}

Contactenlijst/Views/Contact/AdressItem.cshtml
@model ContactCreateViewModel
@Html.EditorFor(model => model.Addresses)

Contactenlijst/Views/Contact/Create.cshtml
@model ContactCreateViewModel

<div class="row">
    <div class="col">
        <form asp-action="Create" asp-controller="Contact" method="post" id="form">
            <div class="form-group">
                <label asp-for="@Model.FirstName"></label> <span class="text-danger" asp-validation-for="@Model.FirstName"></span>
                <input asp-for="@Model.FirstName" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.LastName"></label> <span class="text-danger" asp-validation-for="@Model.LastName"></span>
                <input asp-for="@Model.LastName" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.DateOfBirth"></label> <span class="text-danger" asp-validation-for="@Model.DateOfBirth"></span>
                <input asp-for="@Model.DateOfBirth" class="form-control" />
            </div>
            <div id="emailItemsContainer">
                <span class="text-danger" asp-validation-for="@Model.Emails"></span>
                @Html.EditorFor(model => model.Emails)
            </div>
            <div class="row">
                <div class="col-md-4">
                    <input class="btn btn-primary" type="button" id="btnAddEmailItem" value="Add email" />
                </div>
            </div>
            <div id="phoneNumberItemsContainer">
                <span class="text-danger" asp-validation-for="@Model.PhoneNumbers"></span>
                @Html.EditorFor(model => model.PhoneNumbers)
            </div>
            <div class="row">
                <div class="col-md-4">
                    <input class="btn btn-primary" type="button" id="btnAddPhoneNumberItem" value="Add phone number" />
                </div>
            </div>
            <div id="addressItemsContainer">
                @Html.EditorFor(model => model.Addresses)
            </div>
            <div class="row">
                <div class="col-md-4">
                    <input class="btn btn-primary" type="button" id="btnAddressItem" value="Add address" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Comment"></label> <span class="text-danger" asp-validation-for="@Model.Comment"></span>
                <input asp-for="@Model.Comment" class="form-control" />
            </div>
            <div class="col-md-2">
                <input type="submit" value="Create" id="submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/formDynemicAddSection.min.js"></script>
    <script type="text/javascript">
        AddListItemListener("btnAddEmailItem", "/contact/AddEmailItem", "emailItemsContainer");
        AddListItemListener("btnAddPhoneNumberItem", "/contact/AddPhoneNumberItem", "phoneNumberItemsContainer");
        AddListItemListener("btnAddressItem", "/contact/AddAddressItem", "addressItemsContainer");

        function RemoveAddressItem(id) {
            $.ajax({
                async: true,
                data: $("#form").serialize(),
                type: "POST",
                url: `/contact/RemoveAddressItem/${id}`,
                success: function (str) {
                    document.querySelector(`[modelId="${id}"]`).remove();
                }
            })
           
        }
    </script>
}

Contactenlijst/Views/Contact/EmailItem.cshtml
@model ContactCreateViewModel
@Html.EditorFor(model => model.Emails)

Contactenlijst/Views/Contact/Index.cshtml
@model IEnumerable<ContactIndexViewModel>

<div>
    @if (Model.Any( )) {
        <ul>
            @foreach (ContactIndexViewModel contact in Model) {
                <li>@contact.FullName</li>
            }
        </ul>
    } else {
        <p>Er zijn geen contacten</p>
    }
</div>

Contactenlijst/Views/Contact/PhoneNumberItem.cshtml
@model ContactCreateViewModel
@Html.EditorFor(model => model.PhoneNumbers)